export const REQUEST_HOME_API_DATA = "REQUEST_HOME_API_DATA";
export const RECEIVE_HOME_API_DATA = "RECEIVE_HOME_API_DATA";
export const REQUEST_BLOGS_DATA = "REQUEST_BLOGS_DATA";
export const RECEIVE_BLOGS_DATA = "REQUEST_BLOGS_DATA";
export const REQUEST_CONTACT_DATA = "REQUEST_CONTACT_DATA";
export const RECEIVE_CONTACT_DATA = "RECEIVE_CONTACT_DATA";